version: "3"

services:
  libretranslate-cuda:
    container_name: libretranslate-cuda
    build:
      context: .
      dockerfile: docker/cuda.Dockerfile
    restart: unless-stopped
    ports:
      - "1116:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
